apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lms
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: suhaas4644/cicdproject-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 12345
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/cicdproject?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lms-db-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lms-db-secret
                  key: MYSQL_PASSWORD
            - name: SPRING_MVC_ASYNC_REQUEST_TIMEOUT
              value: "300000"
            - name: SERVER_TOMCAT_CONNECTION_TIMEOUT
              value: "300000"
            - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              value: "300000"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
