apiVersion: v1
kind: Secret
metadata:
  name: lms-db-secret
  namespace: lms
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: Y2ljZHByb2plY3Q=
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=